In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('test_pe.csv')
data

name  Machine  \
0     PE/000958dfc6c455b5106d1e1326698bd4.vir.1      332   
1     PE/000a80f082ef82e04d5396740f288815.vir.1      332   
2     PE/000d09bdcaadf86549118d6be24862cb.vir.1      332   
3     PE/0013418a90e36ffa02d13064fc705144.vir.1      332   
4     PE/0014f80eb7ae874afd50a175441de885.vir.1      332   
...                                         ...      ...   
2655  PE/58ee0787e98e2e65164cdd2bad7b4dd1.vir.1      332   
2656  PE/5908074e0836fd46198d22662e8c3092.vir.1      332   
2657  PE/590a9c6a39005b789983a5d8fa2e9aaf.vir.1      332   
2658  PE/5917c8dd0e745f3ff814c8b1703172e0.vir.1      332   
2659  PE/591a83a4d0075c56878efeefaef7de26.vir.0      332   

      SizeOfOptionalHeader  Characteristics  MajorLinkerVersion  \
0                      224             8450                   8   
1                      224              271                   6   
2                      224              271                   6   
3                      224            33167                   2   
4                      224              271                   6   
...                    ...              ...                 ...   
2655                   224             8450                   8   
2656                   224              259                   8   
2657                   224              271                   6   
2658                   224              775                   2   
2659                   224              258                  12   

      MinorLinkerVersion  SizeOfCode  SizeOfInitializedData  \
0                      0       69632                   8192   
1                      0      237568                 155648   
2                      0       24064                 308224   
3                     25       16896                 205312   
4                      0       23552                 119808   
...                  ...         ...                    ...   
2655                   0       73728                   8192   
2656                   0       57344                 319488   
2657                   0           0                      0   
2658                  56      249856                 289792   
2659                   0      355840                  70656   

      SizeOfUninitializedData  AddressOfEntryPoint  ...  rich_11   rich_12  \
0                           0                74158  ...        0         0   
1                           0               223094  ...        6     65536   
2                        8192                12538  ...        0         0   
3                           0                20284  ...        0         0   
4                        1024                12860  ...        0         0   
...                       ...                  ...  ...      ...       ...   
2655                        0                80478  ...        0         0   
2656                        0                50103  ...       31   9730057   
2657                        0              4690997  ...       44     65536   
2658                     4096                 4672  ...        0         0   
2659                        0               176420  ...       99  13369309   

      rich_13   rich_14  rich_15   rich_16  rich_17   rich_18  rich_19  \
0           0         0        0         0        0         0        0   
1         686   1647610       25         0       44    729064       64   
2           0         0        0         0        0         0        0   
3           0         0        0         0        0         0        0   
4           0         0        0         0        0         0        0   
...       ...       ...      ...       ...      ...       ...      ...   
2655        0         0        0         0        0         0        0   
2656        1   9533449        1         0        0         0        0   
2657      750   1253218       31   9795593        1   1188092       10   
2658        0         0        0         0        0         0        0   
2659     

In [3]:
x = data.drop(['name', 'malware'], axis=1).values
x

array([[3.3200000e+02, 2.2400000e+02, 8.4500000e+03, ..., 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00],
       [3.3200000e+02, 2.2400000e+02, 2.7100000e+02, ..., 4.4000000e+01,
        7.2906400e+05, 6.4000000e+01],
       [3.3200000e+02, 2.2400000e+02, 2.7100000e+02, ..., 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00],
       ...,
       [3.3200000e+02, 2.2400000e+02, 2.7100000e+02, ..., 1.0000000e+00,
        1.1880920e+06, 1.0000000e+01],
       [3.3200000e+02, 2.2400000e+02, 7.7500000e+02, ..., 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00],
       [3.3200000e+02, 2.2400000e+02, 2.5800000e+02, ..., 8.0000000e+00,
        1.4766605e+07, 3.7000000e+01]])

In [4]:
y = data['malware'].values
y

array([1, 1, 1, ..., 1, 1, 0])

In [5]:
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.feature_selection import SelectFromModel

fsel = ExtraTreesClassifier().fit(x, y)
model = SelectFromModel(fsel, prefit=True)
x_new = model.transform(x)
nb_features = x_new.shape[1]
nb_features
x = x_new

In [6]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaler.fit(x)

x_scaled = scaler.fit_transform(x)
x = x_scaled

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3)
x_train.shape, x_test.shape

((1862, 156), (798, 156))

In [9]:
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense, Dropout

In [10]:
model = Sequential()

In [11]:
from tensorflow.keras.layers import Dropout

In [12]:
model.add(Dense(1024, input_dim=x_train.shape[1], activation='relu'))
model.add(Dropout(0.3))
model.add(Dense(1024, activation='relu'))
model.add(Dropout(0.3))
model.add(Dense(1024, activation='relu'))
model.add(Dropout(0.3))
model.add(Dense(1, activation='sigmoid'))

In [13]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [14]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 1024)              160768    
                                                                 
 dropout (Dropout)           (None, 1024)              0         
                                                                 
 dense_1 (Dense)             (None, 1024)              1049600   
                                                                 
 dropout_1 (Dropout)         (None, 1024)              0         
                                                                 
 dense_2 (Dense)             (None, 1024)              1049600   
                                                                 
 dropout_2 (Dropout)         (None, 1024)              0         
                                                                 
 dense_3 (Dense)             (None, 1)                 1

In [15]:
model.fit(x_train, y_train, epochs=100)

Epoch 1/100
59/59 [==============================] - 7s 70ms/step - loss: 0.4478 - accuracy: 0.7825
Epoch 2/100
59/59 [==============================] - 6s 100ms/step - loss: 0.3719 - accuracy: 0.8346
Epoch 3/100
59/59 [==============================] - 4s 69ms/step - loss: 0.3173 - accuracy: 0.8588
Epoch 4/100
59/59 [==============================] - 3s 48ms/step - loss: 0.2935 - accuracy: 0.8716
Epoch 5/100
59/59 [==============================] - 2s 42ms/step - loss: 0.2700 - accuracy: 0.8797
Epoch 6/100
59/59 [==============================] - 3s 51ms/step - loss: 0.2369 - accuracy: 0.8910
Epoch 7/100
59/59 [==============================] - 3s 51ms/step - loss: 0.2237 - accuracy: 0.9023
Epoch 8/100
59/59 [==============================] - 2s 42ms/step - loss: 0.2065 - accuracy: 0.9033
Epoch 9/100
59/59 [==============================] - 3s 46ms/step - loss: 0.2058 - accuracy: 0.9049
Epoch 10/100
59/59 [==============================] - 3s 43ms/step - loss: 0.1902 - accuracy: 0.916

In [16]:
import numpy as np

In [17]:
y_pred = model.predict(x_test)
y_pred

25/25 [==============================] - 0s 7ms/step


array([[9.99984026e-01],
       [9.99998510e-01],
       [1.00000000e+00],
       [9.70742524e-01],
       [1.00000000e+00],
       [9.99965072e-01],
       [1.00000000e+00],
       [8.23443952e-06],
       [2.39739660e-04],
       [7.38425693e-03],
       [9.76965606e-01],
       [1.00000000e+00],
       [1.00000000e+00],
       [5.80876768e-01],
       [9.99585688e-01],
       [3.50289702e-01],
       [1.00000000e+00],
       [2.61255377e-06],
       [9.28329647e-01],
       [1.29445179e-04],
       [1.00000000e+00],
       [1.00000000e+00],
       [1.00000000e+00],
       [1.00000000e+00],
       [2.16594245e-03],
       [3.82869095e-01],
       [1.00000000e+00],
       [7.29272783e-01],
       [9.99813437e-01],
       [1.00000000e+00],
       [6.42299792e-03],
       [9.99989867e-01],
       [9.99999940e-01],
       [1.00000000e+00],
       [9.79888320e-01],
       [1.00000000e+00],
       [1.00000000e+00],
       [1.00000000e+00],
       [1.00000000e+00],
       [9.40560270e-03],


In [18]:
t = []
for val in y_pred:
    t.append(1 if val > 0.5 else 0)
t

[1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,


In [19]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, t)

0.8771929824561403