In [1]:
# Data preprocessing

In [2]:
import pandas as pd

data = pd.read_csv('winequalityN.csv')

In [3]:
data

type  fixed acidity  volatile acidity  citric acid  residual sugar  \
0     white            7.0             0.270         0.36            20.7   
1     white            6.3             0.300         0.34             1.6   
2     white            8.1             0.280         0.40             6.9   
3     white            7.2             0.230         0.32             8.5   
4     white            7.2             0.230         0.32             8.5   
...     ...            ...               ...          ...             ...   
6492    red            6.2             0.600         0.08             2.0   
6493    red            5.9             0.550         0.10             2.2   
6494    red            6.3             0.510         0.13             2.3   
6495    red            5.9             0.645         0.12             2.0   
6496    red            6.0             0.310         0.47             3.6   

      chlorides  free sulfur dioxide  total sulfur dioxide  density    pH  \
0         0.045                 45.0                 170.0  1.00100  3.00   
1         0.049                 14.0                 132.0  0.99400  3.30   
2         0.050                 30.0                  97.0  0.99510  3.26   
3         0.058                 47.0                 186.0  0.99560  3.19   
4         0.058                 47.0                 186.0  0.99560  3.19   
...         ...                  ...                   ...      ...   ...   
6492      0.090                 32.0                  44.0  0.99490  3.45   
6493      0.062                 39.0                  51.0  0.99512  3.52   
6494      0.076                 29.0                  40.0  0.99574  3.42   
6495      0.075                 32.0                  44.0  0.99547  3.57   
6496      0.067                 18.0                  42.0  0.99549  3.39   

      sulphates  alcohol  quality  
0          0.45      8.8        6  
1          0.49      9.5        6  
2          0.44     10.1        6  
3          0.40      9.9        6  
4          0.40      9.9        6  
...         ...      ...      ...  
6492       0.58     10.5        5  
6493        NaN     11.2        6  
6494       0.75     11.0        6  
6495       0.71     10.2        5  
6496       0.66     11.0        6  

[6497 rows x 13 columns]

In [4]:
data['type'].value_counts()

white    4898
red      1599
Name: type, dtype: int64

In [5]:
import numpy as np

In [6]:
data['type'] = np.where(data['type'] == 'white', 1, 0).astype(int)

In [7]:
data.head()

type  fixed acidity  volatile acidity  citric acid  residual sugar  \
0     1            7.0              0.27         0.36            20.7   
1     1            6.3              0.30         0.34             1.6   
2     1            8.1              0.28         0.40             6.9   
3     1            7.2              0.23         0.32             8.5   
4     1            7.2              0.23         0.32             8.5   

   chlorides  free sulfur dioxide  total sulfur dioxide  density    pH  \
0      0.045                 45.0                 170.0   1.0010  3.00   
1      0.049                 14.0                 132.0   0.9940  3.30   
2      0.050                 30.0                  97.0   0.9951  3.26   
3      0.058                 47.0                 186.0   0.9956  3.19   
4      0.058                 47.0                 186.0   0.9956  3.19   

   sulphates  alcohol  quality  
0       0.45      8.8        6  
1       0.49      9.5        6  
2       0.44     10.1        6  
3       0.40      9.9        6  
4       0.40      9.9        6

In [8]:
data = data.dropna(axis=0)

In [9]:
data.isnull().sum()

type                    0
fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

In [10]:
data['quality'].value_counts()

6    2820
5    2128
7    1074
4     214
8     192
3      30
9       5
Name: quality, dtype: int64

In [11]:
x = data.drop(['quality'], axis=1).values
x

array([[ 1.   ,  7.   ,  0.27 , ...,  3.   ,  0.45 ,  8.8  ],
       [ 1.   ,  6.3  ,  0.3  , ...,  3.3  ,  0.49 ,  9.5  ],
       [ 1.   ,  8.1  ,  0.28 , ...,  3.26 ,  0.44 , 10.1  ],
       ...,
       [ 0.   ,  6.3  ,  0.51 , ...,  3.42 ,  0.75 , 11.   ],
       [ 0.   ,  5.9  ,  0.645, ...,  3.57 ,  0.71 , 10.2  ],
       [ 0.   ,  6.   ,  0.31 , ...,  3.39 ,  0.66 , 11.   ]])

In [12]:
y = data['quality'].values
y

array([6, 6, 6, ..., 6, 5, 6])

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

In [15]:
from sklearn.metrics import accuracy_score
from sklearn.ensemble import RandomForestClassifier

In [21]:
!pip install lazypredict

In [22]:
from lazypredict.Supervised import LazyClassifier

In [23]:
clf = LazyClassifier(verbose=0, predictions=True)

In [24]:
models, predictions = clf.fit(x_train, x_test, y_train, y_test)

 90%|████████▉ | 26/29 [00:20<00:01,  1.52it/s]

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000573 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1547
[LightGBM] [Info] Number of data points in the train set: 5170, number of used features: 12
[LightGBM] [Info] Start training from score -5.331752
[LightGBM] [Info] Start training from score -3.374478
[LightGBM] [Info] Start training from score -1.101130
[LightGBM] [Info] Start training from score -0.831498
[LightGBM] [Info] Start training from score -1.808927
[LightGBM] [Info] Start training from score -3.567021
[LightGBM] [Info] Start training from score -6.941190
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with p

100%|██████████| 29/29 [00:21<00:00,  1.35it/s]


In [26]:
models

Accuracy  Balanced Accuracy ROC AUC  F1 Score  \
Model                                                                          
ExtraTreesClassifier               0.69               0.41    None      0.68   
RandomForestClassifier             0.68               0.41    None      0.66   
LGBMClassifier                     0.66               0.40    None      0.65   
LabelPropagation                   0.62               0.40    None      0.62   
LabelSpreading                     0.62               0.40    None      0.61   
DecisionTreeClassifier             0.60               0.39    None      0.60   
BaggingClassifier                  0.63               0.38    None      0.62   
ExtraTreeClassifier                0.59               0.38    None      0.59   
QuadraticDiscriminantAnalysis      0.49               0.35    None      0.48   
KNeighborsClassifier               0.55               0.31    None      0.54   
LinearDiscriminantAnalysis         0.54               0.28    None      0.52   
SVC                                0.58               0.27    None      0.54   
NearestCentroid                    0.26               0.26    None      0.31   
LogisticRegression                 0.54               0.26    None      0.51   
PassiveAggressiveClassifier        0.43               0.25    None      0.42   
CalibratedClassifierCV             0.54               0.24    None      0.49   
Perceptron                         0.42               0.24    None      0.41   
LinearSVC                          0.53               0.23    None      0.46   
BernoulliNB                        0.45               0.23    None      0.43   
RidgeClassifier                    0.53               0.23    None      0.46   
SGDClassifier                      0.52               0.23    None      0.45   
RidgeClassifierCV                  0.53               0.23    None      0.46   
GaussianNB                         0.34               0.22    None      0.37   
AdaBoostClassifier                 0.38               0.17    None      0.37   
DummyClassifier                    0.44               0.17    None      0.27   

                               Time Taken  
Model                                      
ExtraTreesClassifier                 0.80  
RandomForestClassifier               1.33  
LGBMClassifier                       1.14  
LabelPropagation                     2.01  
LabelSpreading                       3.65  
DecisionTreeClassifier               0.07  
BaggingClassifier                    0.37  
ExtraTreeClassifier                  0.03  
QuadraticDiscriminantAnalysis        0.06  
KNeighborsClassifier                 0.18  
LinearDiscriminantAnalysis           0.08  
SVC                                  1.94  
NearestCentroid                      0.03  
LogisticRegression                   0.26  
PassiveAggressiveClassifier          0.07  
CalibratedClassifierCV               6.71  
Perceptron                           0.05  
LinearSVC                            1.85  
BernoulliNB                          0.05  
RidgeClassifier                      0.04  
SGDClassifier                        0.20  
RidgeClassifierCV                    0.05  
GaussianNB                           0.02  
AdaBoostClassifier                   0.42  
DummyClassifier                      0.01

In [16]:
model = RandomForestClassifier()

In [17]:
model.fit(x_train, y_train)

RandomForestClassifier()

In [18]:
y_pred = model.predict(x_test)

In [19]:
y_pred

array([5, 7, 6, ..., 7, 6, 7])

In [20]:
accuracy_score(y_test, y_pred)

0.6821345707656613

In [27]:
from sklearn.metrics import classification_report

for model_name in predictions.columns.tolist():
    print(f'{model_name}')
    print(classification_report(y_test, predictions[model_name]))

AdaBoostClassifier
              precision    recall  f1-score   support

           3       0.00      0.00      0.00         5
           4       0.00      0.00      0.00        37
           5       0.48      0.59      0.53       409
           6       0.48      0.43      0.46       569
           7       0.00      0.00      0.00       227
           8       0.00      0.00      0.00        46

    accuracy                           0.38      1293
   macro avg       0.16      0.17      0.16      1293
weighted avg       0.36      0.38      0.37      1293

BaggingClassifier
              precision    recall  f1-score   support

           3       0.00      0.00      0.00         5
           4       0.00      0.00      0.00        37
           5       0.63      0.75      0.69       409
           6       0.65      0.67      0.66       569
           7       0.62      0.51      0.56       227
           8       0.73      0.35      0.47        46

    accuracy                           0

In [28]:
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.feature_selection import SelectFromModel

fsel = ExtraTreesClassifier().fit(x, y)
model_new = SelectFromModel(fsel, prefit=True)
x_new = model_new.transform(x)
nb_features = x_new.shape[1]

In [29]:
nb_features

6

In [30]:
x_new

array([[  0.27   ,  45.     , 170.     ,   1.001  ,   0.45   ,   8.8    ],
       [  0.3    ,  14.     , 132.     ,   0.994  ,   0.49   ,   9.5    ],
       [  0.28   ,  30.     ,  97.     ,   0.9951 ,   0.44   ,  10.1    ],
       ...,
       [  0.51   ,  29.     ,  40.     ,   0.99574,   0.75   ,  11.     ],
       [  0.645  ,  32.     ,  44.     ,   0.99547,   0.71   ,  10.2    ],
       [  0.31   ,  18.     ,  42.     ,   0.99549,   0.66   ,  11.     ]])

In [31]:
model_new

SelectFromModel(estimator=ExtraTreesClassifier(), prefit=True)

In [34]:
data.head()

type  fixed acidity  volatile acidity  citric acid  residual sugar  \
0     1           7.00              0.27         0.36           20.70   
1     1           6.30              0.30         0.34            1.60   
2     1           8.10              0.28         0.40            6.90   
3     1           7.20              0.23         0.32            8.50   
4     1           7.20              0.23         0.32            8.50   

   chlorides  free sulfur dioxide  total sulfur dioxide  density   pH  \
0       0.04                45.00                170.00     1.00 3.00   
1       0.05                14.00                132.00     0.99 3.30   
2       0.05                30.00                 97.00     1.00 3.26   
3       0.06                47.00                186.00     1.00 3.19   
4       0.06                47.00                186.00     1.00 3.19   

   sulphates  alcohol  quality  
0       0.45     8.80        6  
1       0.49     9.50        6  
2       0.44    10.10        6  
3       0.40     9.90        6  
4       0.40     9.90        6

In [35]:
dir(fsel)

['__abstractmethods__',
 '__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_impl',
 '_check_feature_names',
 '_check_n_features',
 '_compute_oob_predictions',
 '_estimator_type',
 '_get_oob_predictions',
 '_get_param_names',
 '_get_tags',
 '_make_estimator',
 '_more_tags',
 '_parameter_constraints',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_required_parameters',
 '_set_oob_score_and_attributes',
 '_validate_X_predict',
 '_validate_data',
 '_validate_estimator',
 '_validate_params',
 '_validate_y_class_weight',
 'apply',
 'base_estimator',
 'base_estimato

In [40]:
fsel.feature_importances_

array([0.007766  , 0.07982449, 0.09884369, 0.08222261, 0.08315482,
       0.08037822, 0.08467808, 0.09016554, 0.09241899, 0.08218528,
       0.08569381, 0.13266848])

In [46]:
nb_features = x_new.shape[0]

indices = np.argsort(fsel.feature_importances_)[::-1][:nb_features]
for f in range(nb_features):
    print("%d. feature %s (%f)" % (f+1, data.columns[indices[f]], fsel.feature_importances_[indices[f]]))

1. feature alcohol (0.132668)
2. feature volatile acidity (0.098844)
3. feature density (0.092419)
4. feature total sulfur dioxide (0.090166)
5. feature sulphates (0.085694)
6. feature free sulfur dioxide (0.084678)
7. feature residual sugar (0.083155)
8. feature citric acid (0.082223)
9. feature pH (0.082185)
10. feature chlorides (0.080378)
11. feature fixed acidity (0.079824)
12. feature type (0.007766)


IndexError: ignored

In [47]:
x_new.shape

(6463, 6)