In [1]:
import tensorflow as tf
import pandas as pd
import numpy as np

In [2]:
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In [3]:
model = Sequential()

In [4]:
model.add(Dense(10, activation='relu', input_dim=4))
model.add(Dense(5, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

# model.summary()

In [5]:
model.compile(optimizer='adam', loss='mse', metrics=['mae'])

In [6]:
x = [
    [57, 162, 48, 27],
    [23, 158, 52, 62],
    [32, 178, 72, 38],
    [15, 167, 56, 48],
]
y = [0, 0, 1, 1]
len(x), len(y)

(4, 4)

In [7]:
x_train = np.array(x).reshape(-1, 4)
y_train = np.array(y)
x_train

array([[ 57, 162,  48,  27],
       [ 23, 158,  52,  62],
       [ 32, 178,  72,  38],
       [ 15, 167,  56,  48]])

In [8]:
model.fit(x_train, y_train, epochs=100)

Epoch 1/100
1/1 [==============================] - 1s 590ms/step - loss: 0.5000 - mae: 0.5000
Epoch 2/100
1/1 [==============================] - 0s 8ms/step - loss: 0.5000 - mae: 0.5000
Epoch 3/100
1/1 [==============================] - 0s 7ms/step - loss: 0.5000 - mae: 0.5000
Epoch 4/100
1/1 [==============================] - 0s 7ms/step - loss: 0.5000 - mae: 0.5000
Epoch 5/100
1/1 [==============================] - 0s 7ms/step - loss: 0.5000 - mae: 0.5000
Epoch 6/100
1/1 [==============================] - 0s 9ms/step - loss: 0.5000 - mae: 0.5000
Epoch 7/100
1/1 [==============================] - 0s 7ms/step - loss: 0.5000 - mae: 0.5000
Epoch 8/100
1/1 [==============================] - 0s 8ms/step - loss: 0.5000 - mae: 0.5000
Epoch 9/100
1/1 [==============================] - 0s 6ms/step - loss: 0.5000 - mae: 0.5000
Epoch 10/100
1/1 [==============================] - 0s 7ms/step - loss: 0.5000 - mae: 0.5000
Epoch 11/100
1/1 [==============================] - 0s 6ms/step - loss: 0.500

In [9]:
model.predict([[11, 170, 90, 24]])

1/1 [==============================] - 0s 73ms/step


array([[1.]], dtype=float32)

In [10]:
model.predict([[57, 162, 48, 27]])

1/1 [==============================] - 0s 26ms/step


array([[1.]], dtype=float32)